### PR TITLE
Development

### PR DESCRIPTION
**Pull request by ErinPeat**
- Create script for filtering digitalMLPA files on patient specific Pan numbers to remove incidental findings 
- Create batch file so script can be run on a double click
- Create config to facilitate paths etc

- - -
This change is [Reviewable](https://reviewable.io/reviews/moka-guys/digital_mlpa/1)

### CODE REVIEW

**Review by natashapinto — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/digital_mlpa/1)* status: all files reviewed, 1 unresolved discussion (waiting on @ErinPeat)

___
*[`digital_mlpa_filtering.py` line 163 at r2](https://reviewable.io/reviews/moka-guys/digital_mlpa/1#-NAEzDaZ9FFEWxm2bpKw:-NAEzDaZ9FFEWxm2bpKx:bf0ydro) ([raw file](https://github.com/moka-guys/digital_mlpa/blob/8b1af22994fadfb5b5e8cf3ddcd4d5a67f577185/digital_mlpa_filtering.py#L163)):*
> ```Python
>             pan_numbers_with_genes[patient_pan_number] = gene_list
>             error_occurred = False
>             e = " "
> ```

could you give this a proper variable name please

**Review by ErinPeat — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/digital_mlpa/1)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @natashapinto)

___
*[`digital_mlpa_filtering.py` line 163 at r2](https://reviewable.io/reviews/moka-guys/digital_mlpa/1#-NAEzDaZ9FFEWxm2bpKw:-NAIzFShCuZ6-eE10fyr:bs7wub4) ([raw file](https://github.com/moka-guys/digital_mlpa/blob/8b1af22994fadfb5b5e8cf3ddcd4d5a67f577185/digital_mlpa_filtering.py#L163)):*
<details><summary><i>Previously, natashapinto wrote…</i></summary><blockquote>

could you give this a proper variable name please
</blockquote></details>

Done!

**Review by Graeme-Smith — APPROVED** [review]
> Reviewed 1 of 2 files at r3, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/digital_mlpa/1)* status: all files reviewed, 1 unresolved discussion (waiting on @natashapinto)

**Review by Graeme-Smith — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/digital_mlpa/1)* status: all files reviewed, 1 unresolved discussion (waiting on @natashapinto)

**Review by Graeme-Smith — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/digital_mlpa/1)* status: all files reviewed, 1 unresolved discussion (waiting on @natashapinto)

**Review by natashapinto — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/digital_mlpa/1)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ErinPeat)

**Pull request merged**
